### ISSUE TITLE
Investigate replacing charts_flutter with fl_chart for charts in results view

### ISSUE THREAD

**Issue by nstrelow** [hpi-studyu/studyu#12]
charts_flutter is a package from google, but **not** an official package. It is maintained internally at Google and only very seldom receives updates. No PRs are accepted. Last update (before null safety) was over 1 year ago.

fl_chart is a very (the most) popular chart package

**Comment by Ahmadre** [comment]
Did you try: https://pub.dev/packages/syncfusion_flutter_charts

It's totally for free if you don't earn more then 1 million/year or use it in any study cases. Just give them a call. Their support is really kind and great :)

**Comment by nstrelow** [comment]
@Ahmadre Thanks a lot for the recommendation.
I am currently probably not replacing the charts library any time soon.

And I try to only use AFAIK free and open source software. Who knows, maybe this project would like to earn good money at some point (I doubt it^^), but at least maybe more than 4 developer work on it.
Also Syncfusion might change their License at some point.

I guess the risk a very low, but I do not need all the feature they have. Should at some point I need a great library such as the syncfusion one, then I will definitely consider it.
