### ISSUE TITLE
It is possible to answer the same questionaire multiple times

### ISSUE THREAD

**Issue by hig-dev** [hpi-studyu/studyu#585]
**Describe the bug**
It is possible to answer the same questionaire multiple times.

**To Reproduce**
1. Join a study in the app
2. Fill a questionaire and tap on "Complete"
3. Open the completed questionaire again, fill it again, and tap "Complete"
4. The database will show two SubjectProgress items for the same question and subject

**Expected behavior**
After completing the questionaire, it should not be possible to add another subject progress.

**Comment by johannesvedder** [comment]
Have you experienced this with a release build? Because this is a feature in Debug mode.
